import AcUnitIcon from '@mui/icons-material/AcUnit';
import AssessmentIcon from '@mui/icons-material/Assessment';
import BackupIcon from '@mui/icons-material/Backup';
import BubbleChartOutlinedIcon from '@mui/icons-material/BubbleChartOutlined';
import DonutLargeIcon from '@mui/icons-material/DonutLarge';
import ExtensionIcon from '@mui/icons-material/Extension';
import GamesOutlinedIcon from '@mui/icons-material/GamesOutlined';
import GridOnOutlinedIcon from '@mui/icons-material/GridOnOutlined';
import HomeOutlinedIcon from '@mui/icons-material/HomeOutlined';
import LaptopWindowsOutlinedIcon from '@mui/icons-material/LaptopWindowsOutlined';
import InboxIcon from '@mui/icons-material/MoveToInbox';
import SettingsIcon from '@mui/icons-material/Settings';
import TableChartOutlinedIcon from '@mui/icons-material/TableChartOutlined';
import TimelineOutlinedIcon from '@mui/icons-material/TimelineOutlined';
import AccountTreeOutlinedIcon from '@mui/icons-material/AccountTreeOutlined';
import LogoutIcon from '@mui/icons-material/Logout';
import { RouteItems } from 'models';
import { isHidden } from 'utils';

export const analyticsDashboards: RouteItems = [
    {
        label: 'ParetoAnalysis.MenuLabel',
        route: '/paretoAnalysis',
        component: 'ParetoAnalysis',
        componentSPR: 'ParetoAnalysisSpr',
        roles: [],
        disabled: false,
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'FailureRateTrend.PageTitle',
        route: '/failureRateTrend',
        component: 'FailureRateTrend',
        componentSPR: 'FailureRateTrendSpr',
        roles: [],
        disabled: false,
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'FaultCountTrend.PageTitle',
        route: '/faultCountTrend',
        component: 'FaultCountTrend',
        componentSPR: 'FaultCountTrendSpr',
        roles: [],
        disabled: false,
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'EssentialControlChart.MenuTitle',
        route: '/essentialControlChart',
        component: 'EssentialControlChart',
        componentSPR: 'EssentialControlChartSpr',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'TopXFaultCountAnalysis.PageTitle',
        route: '/topXFaultCountAnalysis',
        component: 'TopXFaultCountAnalysis',
        componentSPR: `TopXFaultCountAnalysisSpr`,
        roles: [],
        disabled: false,
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'CarBodyAnalysis.PageTitle',
        route: '/carBodyRiskAnalysis',
        component: 'CarbodyRiskAnalysis',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    // {
    //     label: 'RootCauseVisibility.PageTitle',
    //     route: '/rootCauseVisibility',
    //     component: 'RootCauseVisibility',
    //     roles: [],
    //     disabled: false,
    //     icon: <AccountTreeOutlinedIcon />,
    // },
    {
        label: 'OpportunityAnalysisTool.MenuTitle',
        route: '/opportunityAnalysis',
        component: 'OpportunityAnalysisTool',
        componentSPR: 'OpportunityAnalysisTool',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'CarBodyDurationsPerStation.PageTitle',
        route: '/carBodyDurationsPerStation',
        component: 'CarBodyDurationsPerStation',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'CycleMeasurementCombo.PageTitle',
        route: '/cycleMeasurementCombo',
        component: 'CycleMeasurementCombo',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'Measurements.PageTitle',
        route: '/measurements',
        component: 'Measurements',
        componentSPR: 'MeasurementsSpr',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'UserManagement.PageTitle',
        route: '/userManagement',
        roles: [],
        disabled: isDemoTenant(),
        icon: <AssessmentIcon />,
    },
    /* [INSERT NEW PAGE ROUTE ABOVE]  Needed for generating pages seamlessly */
    {
        label: 'Menu.AvailabilityAndReliabilityTitle',
        route: '/mtbfAnalysis',
        roles: [],
        disabled: false,
        icon: <AccountTreeOutlinedIcon />,
        children: [
            {
                label: 'MtbfAnalysis.MenuTitle',
                route: '/mtbfAnalysis',
                component: 'MtbfAnalysis',
                componentSPR: 'MtbfAnalysisSpr',
                roles: [],
                disabled: false,
                icon: <AccountTreeOutlinedIcon />,
            },
            {
                label: 'MttrAnalysis.MenuTitle',
                route: '/mttrAnalysis',
                component: 'MttrAnalysis',
                componentSPR: 'MttrAnalysisSpr',
                roles: [],
                disabled: false,
                icon: <AccountTreeOutlinedIcon />,
            },
            {
                label: 'TtrAnalysis.PageTitle',
                route: '/ttrAnalysis',
                component: 'TtrAnalysis',
                roles: [],
                disabled: isHidden(['jlr', 'demoStage', 'rivian']),
                icon: <AccountTreeOutlinedIcon />,
            },
            {
                label: 'TaAnalysis.MenuTitle',
                route: '/taAnalysis',
                component: 'TaAnalysis',
                componentSPR: 'TaAnalysisSpr',
                roles: [],
                disabled: false,
                icon: <AccountTreeOutlinedIcon />,
            },
        ],
    },
    {
        label: 'MaintainanceAction.PageTitle',
        route: '/maintenanceAction',
        component: 'MaintainanceAction',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'StationAvailability.PageTitle',
        route: '/stationAvailability',
        component: 'StationAvailability',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'MeasurementTrend.PageTitle',
        route: '/measurementTrend',
        component: 'MeasurementTrend',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'CycleGapTempo.PageTitle',
        route: '/cycleGapTempo',
        component: 'CycleGapTempo',
        componentSPR: 'CyclegapTempoSpr',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler']),
        icon: <AccountTreeOutlinedIcon />,
    },
    // {
    //     label: 'CarBodyDurationPerStation.PageTitle',
    //     route: '/carBodyDurationPerStation',
    //     component: 'CarBodyDurationPerStation',
    //     roles: [],
    //     disabled: isHidden(['v1daimler', 'volvo', 'daimler']),
    //     // disabled: isDemoTenant(),
    //     icon: <AccountTreeOutlinedIcon />,
    // },
    {
        label: 'DailyFaultTrends.PageTitle',
        route: '/dailyFaultTrends',
        component: 'DailyFaultTrends',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'St. Availability Trend',
        route: '/saTrend',
        component: 'SaTrend',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'Graphic Data Analysis',
        route: '/graphDataAnalysis',
        component: 'GraphDataAnalysis',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <AccountTreeOutlinedIcon />,
    },
    // {
    //     label: 'EventOccurrence.PageTitle',
    //     route: '/eventOccurrence',
    //     compionent: 'EventOccurrence',
    //     roles: [],
    //     disabled: false,
    //     icon: <AssessmentIcon />,
    // },
    // {
    //     label: 'FaultRateForecast.PageTitle',
    //     route: '/faultRateForecast',
    //     component: 'FaultRateForecast',
    //     roles: [],
    //     disabled: false,
    //     icon: <AssessmentIcon />,
    // },
];

export const overviewDashboard: RouteItems = [
    {
        label: 'PlantOverview.MenuLabel',
        route: '/plantHealthOverview',
        component: 'PlantHealthOverview',
        componentSPR: 'PlantHealthOverviewSpr',
        roles: [],
        disabled: false,
        icon: <DonutLargeIcon />,
    },
    {
        label: 'SystemOverview.MenuLabel',
        route: '/systemOverview',
        component: 'FleetOverview',
        componentSPR: 'FleetOverview',
        roles: [],
        disabled: false,
        icon: <GamesOutlinedIcon />,
    },
    {
        label: 'Sidebar.EluAnalytics',
        route: '/eluPlatformAnalytics',
        component: 'EluPlatformAnalytics',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <ExtensionIcon />,
    },
];

export const dashboards: RouteItems = [
    {
        label: 'Dashboards',
        route: '/dashboards',
        component: 'DashboardPowerBi',
        roles: [],
        id: '0',
        url: [
            `https://app.powerbi.com/reportEmbed?reportId=468b3722-5c41-4c78-adf3-083b9a095681&autoAuth=true&ctid=d4062de4-74ba-4730-a339-59645ae170de&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXVzLWVhc3QyLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0LyJ9&filterPaneEnabled=false`,
            `https://app.powerbi.com/reportEmbed?reportId=a0bef869-7af8-41fa-abd1-4ba5572d2797&autoAuth=true&ctid=d4062de4-74ba-4730-a339-59645ae170de&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXVzLWVhc3QyLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0LyJ9&filterPaneEnabled=false`,
            `https://app.powerbi.com/reportEmbed?reportId=a4c6fdb9-7ddc-4eac-a45a-c1e37c5f74d9&autoAuth=true&ctid=d4062de4-74ba-4730-a339-59645ae170de&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXVzLWVhc3QyLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0LyJ9&filterPaneEnabled=false`,
        ],
        icon: <LaptopWindowsOutlinedIcon />,
        disabled: false,
        children: [],
    },
    {
        label: 'SummaryDashboard.PageTitle',
        route: '/dashboards',
        component: 'DashboardPowerBi',
        id: '1',
        roles: [],
        url: `https://app.powerbi.com/reportEmbed?reportId=468b3722-5c41-4c78-adf3-083b9a095681&autoAuth=true&ctid=d4062de4-74ba-4730-a339-59645ae170de&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXVzLWVhc3QyLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0LyJ9&filterPaneEnabled=false`,
        disabled: false,
        children: [],
        icon: <GridOnOutlinedIcon />,
    },
    {
        label: 'PlantLevelKpi.PageTitle',
        route: '/dashboards',
        component: 'DashboardPowerBi',
        id: '2',
        roles: [],
        url: `https://app.powerbi.com/reportEmbed?reportId=a0bef869-7af8-41fa-abd1-4ba5572d2797&autoAuth=true&ctid=d4062de4-74ba-4730-a339-59645ae170de&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXVzLWVhc3QyLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0LyJ9&filterPaneEnabled=false`,
        disabled: false,
        children: [],
        icon: <AcUnitIcon />,
    },
    {
        label: 'LabAnalysis.PageTitle',
        route: '/dashboards',
        component: 'DashboardPowerBi',
        id: '3',
        roles: [],
        url: `https://app.powerbi.com/reportEmbed?reportId=a4c6fdb9-7ddc-4eac-a45a-c1e37c5f74d9&autoAuth=true&ctid=d4062de4-74ba-4730-a339-59645ae170de&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXVzLWVhc3QyLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0LyJ9&filterPaneEnabled=false`,
        disabled: false,
        children: [],
        icon: <BubbleChartOutlinedIcon />,
    },
];
const programDashboard: RouteItems = [
    {
        label: 'Program.PageTitle',
        route: '/program',
        component: 'Program',
        componentSPR: 'Program',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        icon: <DonutLargeIcon />,
    },
];

export const routes: RouteItems = [
    {
        label: 'HomePage.PageTitle',
        route: '/home',
        component: 'LandingPage',
        componentSPR: 'LandingPage',
        roles: [],
        disabled: false,
        icon: <HomeOutlinedIcon />,
    },
    {
        label: 'Program.PageTitle',
        route: '/program',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        children: [...programDashboard],
        icon: <DonutLargeIcon />,
    },
    {
        label: 'Overview',
        route: '/plantHealthOverview',
        roles: [],
        disabled: false,
        children: [...overviewDashboard],
        icon: <DonutLargeIcon />,
    },
    {
        label: 'ReportingViewPageB.PageTitle',
        route: '/reportingViewB',
        component: 'ReportingViewB',
        componentSPR: 'ReportingViewBspr',
        roles: [],
        disabled: false,
        icon: <TableChartOutlinedIcon />,
    },

    {
        label: 'ReportingViewPage.PageTitle',
        route: '/reportingView',
        component: 'ReportingView',
        componentSPR: 'ReportingViewSpr',
        roles: [],
        disabled: false,
        icon: <AssessmentIcon />,
    },
    {
        label: 'ProcessLogView.PageTitle',
        route: '/processLog',
        component: 'ProcessLogView',
        componentSPR: 'ProcessLogViewSpr',
        roles: [],
        disabled: isHidden(['v1daimler', 'volvo', 'daimler']),
        icon: <TimelineOutlinedIcon />,
    },
    {
        label: 'Sidebar.Analytics',
        route: '/paretoAnalysis',
        roles: [],
        disabled: false,
        children: [...analyticsDashboards],
        icon: <AccountTreeOutlinedIcon />,
    },
    {
        label: 'Sidebar.DashboardKPIs',
        route: '/dashboards',
        roles: [],
        disabled: isHidden(['v1daimler', 'jlr', 'demoStage', 'rivian']),
        children: [...dashboards],
        icon: <InboxIcon />,
    },
    {
        label: 'FileUpload.Title',
        route: '/upload',
        roles: [],
        disabled: isHidden(['demo', 'v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
        children: [
            {
                label: 'FileUpload.Title',
                route: '/upload',
                component: 'FileUpload',
                componentSPR: 'FileUpload',
                roles: [],
                disabled: isHidden(['demo', 'v1daimler', 'volvo', 'daimler', 'jlr', 'demoStage', 'rivian']),
                icon: <BackupIcon />,
            },
        ],
        icon: <BackupIcon />,
    },
    { label: '-' },
    {
        label: 'Settings',
        route: '/settings',
        component: 'Settings',
        roles: [],
        disabled: isHidden(['v1daimler']),
        icon: <SettingsIcon />,
    },
    {
        label: 'Sidebar.Logout',
        route: '/signin',
        component: 'SignIn',
        roles: [],
        disabled: false,
        icon: <LogoutIcon />,
    },
    // [INSERT NEW PAGE COMPONENT ABOVE]  Needed for generating pages seamlessly
];

export const dashboardIcons = {
    Dashboards: 'laptop',
    'SummaryDashboard.PageTitle': 'th',
    'PlantLevelKpi.PageTitle': 'snowflake',
    'LabAnalysis.PageTitle': 'line-chart',
};

export const extras: RouteItems = [
    {
        children: [],
        disabled: false,
        icon: <BubbleChartOutlinedIcon />,
        id: '1002',
        label: 'Dashboard.CycleGapTempo',
        roles: [],
        route: '/dashboards',
        component: 'DashboardPowerBi',
        url: `https://cnvrg-job-webapp-zylw38mhgjrdmxcfzd2z-dash.cnvrg.rmdconnect.io/?`,
    },
    {
        children: [],
        disabled: false,
        icon: <BubbleChartOutlinedIcon />,
        id: '1003',
        label: 'Dashboard.MeasurementTrends',
        roles: [],
        route: '/dashboards',
        component: 'DashboardPowerBi',
        url: `https://cnvrg-job-webapp-djnymanyhutiodgvsels-dash.cnvrg.rmdconnect.io/?`,
    },
    {
        children: [],
        disabled: false,
        icon: <BubbleChartOutlinedIcon />,
        id: '1004',
        label: 'Dashboard.DailyFaultTrends',
        roles: [],
        route: '/dashboards',
        component: 'DashboardPowerBi',
        url: `https://cnvrg-job-webapp-m9ij3z1xsyu5ypqdx2m4-dash.cnvrg.rmdconnect.io/?`,
    },
    {
        children: [],
        disabled: false,
        icon: <BubbleChartOutlinedIcon />,
        id: '1005',
        label: 'Dashboard.StationAvailabilityReport',
        roles: [],
        route: '/dashboards',
        component: 'DashboardPowerBi',
        url: `https://cnvrg-job-webapp-y78boht6n1stdazsaqb4-dash.cnvrg.rmdconnect.io/?`,
    },
    {
        children: [],
        disabled: false,
        icon: <BubbleChartOutlinedIcon />,
        id: '1006',
        label: 'Dashboard.StationAvailabilityTrend',
        roles: [],
        route: '/dashboards',
        component: 'DashboardPowerBi',
        url: `https://cnvrg-job-webapp-ozwv8ycxf8xuuqazwoak-dash.cnvrg.rmdconnect.io/?`,
    },
    {
        children: [],
        disabled: false,
        icon: <BubbleChartOutlinedIcon />,
        id: '1009',
        label: 'Dashboard.CarbodyDurationPerStation',
        roles: [],
        route: '/dashboards',
        component: 'DashboardPowerBi',
        url: `https://cnvrg-job-webapp-jbpbbluo41k7rsfwh4rq-dash.cnvrg.rmdconnect.io/?`,
    },
    {
        children: [],
        disabled: false,
        icon: <BubbleChartOutlinedIcon />,
        id: '1007',
        label: 'Dashboard.GraphicDataAnalysis',
        roles: [],
        route: '/dashboards',
        component: 'DashboardPowerBi',
        url: `https://cnvrg-job-webapp-ilywsbt3dpapjarwsals-dash.cnvrg.rmdconnect.io/?`,
    },
    {
        children: [],
        disabled: false,
        icon: <BubbleChartOutlinedIcon />,
        id: '1008',
        label: 'Dashboard.CarbodyDuration',
        roles: [],
        route: '/dashboards',
        component: 'DashboardPowerBi',
        url: `https://cnvrg-job-webapp-hy8kpbcokyqvregwdgh8-dash.cnvrg.rmdconnect.io/?`,
    },
];
export default routes;
